name: "vulnerawise"
version: "0.0.1"
repository: github.com/vulnerawise/trivy-plugin-vulnerawise
maintainer: yourname
summary: Scan images and repositories, then send results to Vulnerawise API
description: |-
  A Trivy plugin that scans a repository, image, or SBOM (or Kubernetes resource via kubectl/oc)
  and pipes the JSON output to vulnerawise audit.
platforms:
  - selector:
      os: linux
      arch: amd64
    uri: https://github.com/vulnerawise/trivy-plugin-vulnerawise/releases/download/v0.0.1/trivy-vulnerawise.tar.gz 
    bin: ./trivy-vulnerawise
  - selector:
      os: darwin
      arch: amd64
    uri: https://github.com/vulnerawise/trivy-plugin-vulnerawise/releases/download/v0.0.1/trivy-vulnerawise.tar.gz 
    bin: ./trivy-vulnerawise
  - selector:
      os: darwin
      arch: arm64
    uri: https://github.com/vulnerawise/trivy-plugin-vulnerawise/releases/download/v0.0.1/trivy-vulnerawise.tar.gz 
    bin: ./trivy-vulnerawise
